version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
  win: circleci/windows@2.2.0

workflows:
  main_branch:
    jobs:
      - tests:
          filters:
            branches:
              only:
                - main
      - build-and-push-docker-image:
          requires:
            - tests
      - heroku-deploy:
          requires:
            - build-and-push-docker-image

  other_branches:
    jobs:
      - tests:
          filters:
            branches:
              ignore:
                - main

jobs:
  tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Django tests
          command: pytest
      - run:
          name: linting
          command: flake8

  build-and-push-docker-image:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USER/oc-lettings-site:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker tag $DOCKER_USER/oc-lettings-site:$CIRCLE_SHA1 $DOCKER_USER/oc-lettings-site:latest
            docker push $DOCKER_USER/oc-lettings-site:$CIRCLE_SHA1
            docker push $DOCKER_USER/oc-lettings-site:latest

  heroku-deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: heroku maintenance:on --app $HEROKU_APP_NAME
      - run: heroku config:set BUILD_NUMBER=$CIRCLE_BUILD_NUM -a $HEROKU_APP_NAME
      - run: heroku config:set SECRET_KEY=$SECRET_KEY -a $HEROKU_APP_NAME
      - run: heroku config:set SENTRY_DSN=$SENTRY_DSN -a $HEROKU_APP_NAME
      - run: heroku stack:set heroku-20 -a $HEROKU_APP_NAME
      - run: heroku maintenance:off -a $HEROKU_APP_NAME
      - run: heroku run python manage.py migrate -a $HEROKU_APP_NAME #todo require this line
      - run: heroku run python manage.py -x collectstatic --noinput -a $HEROKU_APP_NAME
      - run: heroku run python manage.py -x init_sample_data -a $HEROKU_APP_NAME # (create superuser with orm, populate db...)
      - heroku/deploy-via-git