version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
  win: circleci/windows@2.2.0

workflows:
  main_branch:
    jobs:
      - tests:
          filters:
            branches:
              only:
                - main
      - build-docker-image:
          requires:
            - tests
      - push-docker-image:
          requires:
            - build-docker-image

  other_branches:
    jobs:
      - tests:
          filters:
            branches:
              ignore:
                - main

jobs:
  tests:
#    docker:
#      - image: cimg/python:3.10
#      - image: cimg/base:current
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run pytest
          command: pytest
      - run:
          name: linting
          command: flake8

  build-docker-image:
#    executor: win/default
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_USER/oc-lettings-site:latest .
#          command: docker build -t web:latest .
  push-docker-image:
#    executor: win/default
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker tag $DOCKER_USER/oc-lettings-site:lastest
            docker push $DOCKER_USER/oc-lettings-site:$CIRCLE_SHA1
            docker push $DOCKER_USER/oc-lettings-site:lastest

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: heroku maintenance:on --app $HEROKU_APP_NAME
      - run: heroku config:set BUILD_NUMBER=$CIRCLE_BUILD_NUM -a $HEROKU_APP_NAME
      - run: heroku config:set SECRET_KEY=$SECRET_KEY -a $HEROKU_APP_NAME
      - run: heroku config:set SENTRY_DSN=$SENTRY_DSN -a $HEROKU_APP_NAME
      - run: heroku stack:set heroku-20 -a $HEROKU_APP_NAME
      - run: heroku maintenance:off --app $HEROKU_APP_NAME
      - heroku/deploy-via-git:
          force: true