# Generated by Django 3.0 on 2022-03-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'adress', 'verbose_name_plural': 'addresses'},
        ),
    ]
