# Generated by Django 3.0 on 2022-03-22 13:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oc_lettings_site', '0002_auto_20220321_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='OldProfile',
        ),
    ]
